.TH re 8 "2025-08-18" "1.0" "System Manager's Manual"
.SH NAME
resv \- Start and monitor service
.SH SYNOPSIS
resv <ATTEMPTS> <SLEEP_TIME> <COMMAND>
.SH DESCRIPTION
Resv starts service and monitors its exit status. If its not equal to 0, it retries in <SLEEP_TIME> seconds.
It tries to restart it <ATTEMPTS> times. If it wont work, it exists and forgets about its service.
.SH SEE ALSO
re(8), re-poweroff(8), re-reboot(8)
.SH AUTHOR
Zerfithel